server:
  port: 8005
  id: 0
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rule
  datasource:
    url: jdbc:mysql://192.168.13.170:3306/rule?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Root!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    timeout: 10000ms
    # Redis服务器地址
    host: 192.168.13.171
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: iampassword
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
    max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池中的最小空闲连接
    min-idle: 0
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 100MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入

rule:
  class:
    path: D:\testCode\code\
  jar:
    path: D:\testCode\jar\
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapperLocations: classpath*:mapper/*.xml
